services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: talent_budget_tracker
    ports:
      - "5435:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/talent_budget_tracker?sslmode=disable

  neo4j:
    image: neo4j:5
    environment:
      NEO4J_AUTH: neo4j/password
      NEO4J_dbms_memory_pagecache_size: 1G
      NEO4J_server_memory_heap_initial__size: 512m
      NEO4J_server_memory_heap_max__size: 512m
    ports:
      - "7474:7474"  # Browser
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data

  employee-service:
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    environment:
      POSTGRES_DSN: postgres://postgres:password@db:5432/talent_budget_tracker?sslmode=disable
      NEO4J_URI: bolt://neo4j:7687
      NEO4J_USER: neo4j
      NEO4J_PASSWORD: password
      PORT: "8083"
    depends_on:
      db:
        condition: service_healthy
      neo4j:
        condition: service_started
    restart: on-failure
    ports:
      - "8083:8083"

  budget-service:
    build:
      context: ./budget-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/talent_budget_tracker
      - PORT=8082
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8082:8082"

  resume-screening-service:
    build:
      context: ./resume-screening-service
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/talent_budget_tracker?sslmode=disable
      - PORT=8084
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8084:8084"
    volumes:
      - ./resume-screening-service/resumes:/app/resumes
      - ./resume-screening-service/job_descriptions:/app/job_descriptions
      - ./resume-screening-service/uploads:/app/uploads

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - PORT=4000
      - RESUME_SCREENING_SERVICE_URL=http://resume-screening-service:8084
      - AUTH_SERVICE_URL=http://auth-service:8081
      - EMPLOYEE_SERVICE_URL=http://employee-service:8083
      - BUDGET_SERVICE_URL=http://budget-service:8082
    depends_on:
      - auth-service
      - employee-service
      - budget-service
      - resume-screening-service
    ports:
      - "4000:4000"
    restart: on-failure

volumes:
  pg_data:
  neo4j_data:
